package My_Forms;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Nguyễn Văn Khoa
 */
public class BookInforCardForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    My_Classes.Book book = new My_Classes.Book();
    My_Classes.Author author = new My_Classes.Author();
    My_Classes.Genres genre = new My_Classes.Genres();
    My_Classes.Func_Class func = new My_Classes.Func_Class();

    public BookInforCardForm(int book_id) {
        initComponents();
        this.setLocationRelativeTo(null);

        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(61, 20, 96));
        jPanel1.setBorder(panelHeaderBorder);

        //display image        
        func.displayImage(100, 100, null, "/My_Images/icons8_book_reading_100px.png", jLabel_Form_Title);

        //border the image
        Border JlaBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Image1.setBorder(JlaBorder);

        //add a default image
        func.displayImage(237, 170, null, "/My_Images/icons8_book_100px_2.png", jLabel_Image1);

        //display the book infor
        displayBookInfo(book_id);
    }

    //creat a func to display the book infor
    public void displayBookInfo(int _book_id) {
        try {
            My_Classes.Book selectedBook = book.getBookById(_book_id);

            if (selectedBook != null) {
                jLabel_ISBN.setText(selectedBook.getIsbn());
                jLabel_Name.setText(selectedBook.getName());

                //we need to display the author name
                jLabel_Author.setText(author.getAuthorByID(selectedBook.getAuthor_id()).getFirstName()
                        + " " + author.getAuthorByID(selectedBook.getAuthor_id()).getLastName());

                //we need to display the Genres name
                jLabel_Genre.setText(genre.getGenresID(selectedBook.getGenre_id()).getName());
                jLabel_Publisher.setText(selectedBook.getPublisher());
                jLabel_Price.setText(Double.toString(selectedBook.getPrice()));
                jLabel_Quanlity.setText(Integer.toString(selectedBook.getQuanlity()));
                jLabel_DateRe.setText(selectedBook.getDate_received());
                jTextArea_Desciption.setText(selectedBook.getDescription());

                //display image:
                byte[] image = selectedBook.getCover();
                //we will display the image using the imagebyte
                //so we will made the image path null
                func.displayImage(300, 280, image, "", jLabel_Image1);
            } else {

            }
        } catch (SQLException ex) {
            Logger.getLogger(BookInforCardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Image1 = new javax.swing.JLabel();
        jLabel_ISBN = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Genre = new javax.swing.JLabel();
        jLabel_Author = new javax.swing.JLabel();
        jLabel_Publisher = new javax.swing.JLabel();
        jLabel_Price = new javax.swing.JLabel();
        jLabel_DateRe = new javax.swing.JLabel();
        jLabel_Quanlity = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Desciption = new javax.swing.JTextArea();

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Form_Title.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Form_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("Book Infor Card");
        jLabel_Form_Title.setOpaque(true);

        jLabel_Close.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.setOpaque(true);
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel_Image1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image1.setOpaque(true);

        jLabel_ISBN.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ISBN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_ISBN.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_ISBN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_ISBN.setText("ISBN:");
        jLabel_ISBN.setOpaque(true);

        jLabel_Name.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Name.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_Name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Name.setText("Name:");
        jLabel_Name.setOpaque(true);

        jLabel_Genre.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Genre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Genre.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_Genre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Genre.setText("Genre:");
        jLabel_Genre.setOpaque(true);

        jLabel_Author.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Author.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Author.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_Author.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Author.setText("Author:");
        jLabel_Author.setOpaque(true);

        jLabel_Publisher.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Publisher.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Publisher.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_Publisher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Publisher.setText("Publisher:");
        jLabel_Publisher.setOpaque(true);

        jLabel_Price.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Price.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_Price.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Price.setText("Price:");
        jLabel_Price.setOpaque(true);

        jLabel_DateRe.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_DateRe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_DateRe.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_DateRe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_DateRe.setText("Date Received:");
        jLabel_DateRe.setOpaque(true);

        jLabel_Quanlity.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Quanlity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Quanlity.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_Quanlity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Quanlity.setText("Quanlity:");
        jLabel_Quanlity.setOpaque(true);

        jTextArea_Desciption.setColumns(20);
        jTextArea_Desciption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea_Desciption.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Desciption);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Publisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Genre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_DateRe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Quanlity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_ISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Author)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Publisher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Quanlity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_DateRe))
                    .addComponent(jLabel_Image1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Author;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_DateRe;
    private javax.swing.JLabel jLabel_Form_Title;
    private javax.swing.JLabel jLabel_Genre;
    private javax.swing.JLabel jLabel_ISBN;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Image1;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Price;
    private javax.swing.JLabel jLabel_Publisher;
    private javax.swing.JLabel jLabel_Quanlity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Desciption;
    // End of variables declaration//GEN-END:variables
}
