package My_Forms;

import My_Classes.Func_Class;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;
import javax.swing.JLabel;

/**
 *
 * @author Nguyễn Văn Khoa
 */
public class DashBoardForm extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardForm
     */
    //the button border
    Border buttonBorder1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
    Border buttonBorder2 = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(36, 37, 42));

    My_Classes.Func_Class func = new Func_Class();
    My_Classes.Book book = new My_Classes.Book();

    //creat the jlable array to display the latest 5 book
    JLabel[] jLabels_tab = new JLabel[5];

    public DashBoardForm() {
        initComponents();
        this.setLocationRelativeTo(null);

        //func form class Func_Class using display for dasboard left side
        func.displayImage(jLabel_DashBoard_Logo.getWidth(), jLabel_DashBoard_Logo.getHeight(), null, "/My_Images/icons8_library_64px_3.png", jLabel_DashBoard_Logo);

        //add a border to the panel header
        Border panelHeaderBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jPanel_Header.setBorder(panelHeaderBorder);

        //add effect to the button
        buttonsHoverEffect();

        //add border to the button
        addBorders();

        //display book count:
        displayCount();

        //display border book_cover
        //add black border for the jlable image
        Border panelImageBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.BLACK);
        jLabel_Image_1.setBorder(panelImageBorder);
        jLabel_Image_2.setBorder(panelImageBorder);
        jLabel_Image_3.setBorder(panelImageBorder);
        jLabel_Image_4.setBorder(panelImageBorder);
        jLabel_Image_5.setBorder(panelImageBorder);
        

        //display book cover latest;
        //1- add to the lable[]
        jLabels_tab[0] = jLabel_Image_1;
        jLabels_tab[1] = jLabel_Image_2;
        jLabels_tab[2] = jLabel_Image_3;
        jLabels_tab[3] = jLabel_Image_4;
        jLabels_tab[4] = jLabel_Image_5;
        //2- display the image
        book.displayBooksCover(jLabels_tab);

        
        init();
    }
    
    private void init() {
        titleBar.initJFram(this);
        
    }

    //add a func to add a Border to all the button in the Jpanel menu
    public void addBorders() {
        Component[] comps = jPanel_Menu.getComponents();

        for (Component comp : comps) {
            //check if the component is a button
            if (comp instanceof JButton) {
                JButton button = (JButton) comp;
                //add border
                button.setBorder(buttonBorder2);

            }
        }
    }

    //creat a funtion to add a effect for menu button
    public void buttonsHoverEffect() {
        //get all the conponent in the Jpanel_menu
        Component[] comps = jPanel_Menu.getComponents();

        for (Component comp : comps) {
            //check if the component is a button
            if (comp instanceof JButton) {
                JButton button = (JButton) comp;
                //add a Acction we want
                button.addMouseListener(new MouseAdapter() {

                    @Override
                    public void mouseEntered(MouseEvent evt) {
                        button.setBorder(buttonBorder1);
                    }

                    @Override
                    public void mouseExited(MouseEvent evt) {
                        button.setBorder(buttonBorder2);
                    }
                });
            }
        }
    }

    public void displayCount() {
        jLabel_Book_Count.setText(String.valueOf(func.countData("books")));
        jLabel_Members_Count.setText(String.valueOf(func.countData("members")));
        jLabel5.setText(String.valueOf(func.countData("author")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Menu = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel_DashBoard_Text = new javax.swing.JLabel();
        jLabel_DashBoard_Logo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton_Manager_Genres = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton_Manager_Author = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton_Edit_Member = new javax.swing.JButton();
        jButton_Add_Member = new javax.swing.JButton();
        jButton_Delete_Member = new javax.swing.JButton();
        jButton_MembersList = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton_Add_Book = new javax.swing.JButton();
        jButton_Edit_Book = new javax.swing.JButton();
        jButton_Delete_Book = new javax.swing.JButton();
        jButton_BookList = new javax.swing.JButton();
        jLabel_Circulation = new javax.swing.JLabel();
        jButton_Issue_Book = new javax.swing.JButton();
        jButton_Return_Book = new javax.swing.JButton();
        jLabel_CanLe = new javax.swing.JLabel();
        jButton_ManagerUser = new javax.swing.JButton();
        jPanel_1 = new javax.swing.JPanel();
        jPanel1_Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Book_Count = new javax.swing.JLabel();
        jPanel_2 = new javax.swing.JPanel();
        jPanel2_Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Members_Count = new javax.swing.JLabel();
        jPanel_3 = new javax.swing.JPanel();
        jPanel3_Header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_5 = new javax.swing.JPanel();
        jPanel5_Header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Image_2 = new javax.swing.JLabel();
        jLabel_Image_3 = new javax.swing.JLabel();
        jLabel_Image_4 = new javax.swing.JLabel();
        jLabel_Image_5 = new javax.swing.JLabel();
        jLabel_Image_1 = new javax.swing.JLabel();
        jLabel_Welcome_UserName = new javax.swing.JLabel();
        titleBar = new javaswingdev.swing.titlebar.TitleBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Menu.setBackground(new java.awt.Color(36, 37, 42));

        jPanel_Header.setBackground(new java.awt.Color(1, 50, 67));

        jLabel_DashBoard_Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_DashBoard_Text.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DashBoard_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DashBoard_Text.setText("Library");

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_DashBoard_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_DashBoard_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_DashBoard_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel_DashBoard_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Genres");

        jButton_Manager_Genres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Manager_Genres.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Manager_Genres.setText("Manager Genres");
        jButton_Manager_Genres.setContentAreaFilled(false);
        jButton_Manager_Genres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Manager_Genres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Manager_GenresActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Authors");

        jButton_Manager_Author.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Manager_Author.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Manager_Author.setText("Manager Authors");
        jButton_Manager_Author.setContentAreaFilled(false);
        jButton_Manager_Author.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Manager_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Manager_AuthorActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Members");

        jButton_Edit_Member.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Edit_Member.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_Member.setText("Edit Members");
        jButton_Edit_Member.setContentAreaFilled(false);
        jButton_Edit_Member.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_MemberActionPerformed(evt);
            }
        });

        jButton_Add_Member.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Add_Member.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Member.setText("Add Members");
        jButton_Add_Member.setContentAreaFilled(false);
        jButton_Add_Member.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_MemberActionPerformed(evt);
            }
        });

        jButton_Delete_Member.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Delete_Member.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Delete_Member.setText("Delete Members");
        jButton_Delete_Member.setContentAreaFilled(false);
        jButton_Delete_Member.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Delete_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_MemberActionPerformed(evt);
            }
        });

        jButton_MembersList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_MembersList.setForeground(new java.awt.Color(255, 255, 255));
        jButton_MembersList.setText("Members List");
        jButton_MembersList.setContentAreaFilled(false);
        jButton_MembersList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_MembersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MembersListActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Books");

        jButton_Add_Book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Add_Book.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Book.setText("Add Books");
        jButton_Add_Book.setContentAreaFilled(false);
        jButton_Add_Book.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_BookActionPerformed(evt);
            }
        });

        jButton_Edit_Book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Edit_Book.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_Book.setText("Edit Books");
        jButton_Edit_Book.setContentAreaFilled(false);
        jButton_Edit_Book.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_BookActionPerformed(evt);
            }
        });

        jButton_Delete_Book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Delete_Book.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Delete_Book.setText("Delete Books");
        jButton_Delete_Book.setContentAreaFilled(false);
        jButton_Delete_Book.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Delete_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_BookActionPerformed(evt);
            }
        });

        jButton_BookList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_BookList.setForeground(new java.awt.Color(255, 255, 255));
        jButton_BookList.setText("Books List");
        jButton_BookList.setContentAreaFilled(false);
        jButton_BookList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_BookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BookListActionPerformed(evt);
            }
        });

        jLabel_Circulation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Circulation.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Circulation.setText("Circulation");

        jButton_Issue_Book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Issue_Book.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Issue_Book.setText("Issue Book");
        jButton_Issue_Book.setContentAreaFilled(false);
        jButton_Issue_Book.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Issue_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Issue_BookActionPerformed(evt);
            }
        });

        jButton_Return_Book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Return_Book.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Return_Book.setText("Return Book");
        jButton_Return_Book.setContentAreaFilled(false);
        jButton_Return_Book.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Return_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Return_BookActionPerformed(evt);
            }
        });

        jLabel_CanLe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_CanLe.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CanLe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CanLe.setText("|");

        jButton_ManagerUser.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_ManagerUser.setForeground(new java.awt.Color(255, 50, 108));
        jButton_ManagerUser.setText("Manager Users");
        jButton_ManagerUser.setContentAreaFilled(false);
        jButton_ManagerUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ManagerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ManagerUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Manager_Genres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Manager_Author, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Add_Member, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Edit_Member, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Delete_Member, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_MembersList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Add_Book, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Edit_Book, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Delete_Book, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_BookList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_ManagerUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_MenuLayout.createSequentialGroup()
                        .addComponent(jButton_Issue_Book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_CanLe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Return_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addComponent(jLabel_Circulation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Manager_Genres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Manager_Author)
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Add_Member)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Edit_Member)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Delete_Member)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_MembersList)
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Add_Book)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Edit_Book)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Delete_Book)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_BookList)
                .addGap(15, 15, 15)
                .addComponent(jLabel_Circulation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Issue_Book)
                    .addComponent(jButton_Return_Book)
                    .addComponent(jLabel_CanLe))
                .addGap(18, 18, 18)
                .addComponent(jButton_ManagerUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Add_Member, jButton_Delete_Member, jButton_Edit_Member, jButton_Manager_Author, jButton_Manager_Genres});

        jPanel_1.setBackground(new java.awt.Color(255, 153, 153));

        jPanel1_Header.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BOOKS");

        javax.swing.GroupLayout jPanel1_HeaderLayout = new javax.swing.GroupLayout(jPanel1_Header);
        jPanel1_Header.setLayout(jPanel1_HeaderLayout);
        jPanel1_HeaderLayout.setHorizontalGroup(
            jPanel1_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_HeaderLayout.setVerticalGroup(
            jPanel1_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Book_Count.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Book_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Book_Count.setText("12451");

        javax.swing.GroupLayout jPanel_1Layout = new javax.swing.GroupLayout(jPanel_1);
        jPanel_1.setLayout(jPanel_1Layout);
        jPanel_1Layout.setHorizontalGroup(
            jPanel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Book_Count, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_1Layout.setVerticalGroup(
            jPanel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_1Layout.createSequentialGroup()
                .addComponent(jPanel1_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel_Book_Count)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        jPanel_2.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2_Header.setBackground(new java.awt.Color(0, 245, 223));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("MEMBERS");

        javax.swing.GroupLayout jPanel2_HeaderLayout = new javax.swing.GroupLayout(jPanel2_Header);
        jPanel2_Header.setLayout(jPanel2_HeaderLayout);
        jPanel2_HeaderLayout.setHorizontalGroup(
            jPanel2_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel2_HeaderLayout.setVerticalGroup(
            jPanel2_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Members_Count.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Members_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Members_Count.setText("12451");

        javax.swing.GroupLayout jPanel_2Layout = new javax.swing.GroupLayout(jPanel_2);
        jPanel_2.setLayout(jPanel_2Layout);
        jPanel_2Layout.setHorizontalGroup(
            jPanel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2_Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Members_Count, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_2Layout.setVerticalGroup(
            jPanel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_2Layout.createSequentialGroup()
                .addComponent(jPanel2_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel_Members_Count)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        jPanel_3.setBackground(new java.awt.Color(102, 153, 255));

        jPanel3_Header.setBackground(new java.awt.Color(102, 180, 242));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("AUTHORS");

        javax.swing.GroupLayout jPanel3_HeaderLayout = new javax.swing.GroupLayout(jPanel3_Header);
        jPanel3_Header.setLayout(jPanel3_HeaderLayout);
        jPanel3_HeaderLayout.setHorizontalGroup(
            jPanel3_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel3_HeaderLayout.setVerticalGroup(
            jPanel3_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("124511");

        javax.swing.GroupLayout jPanel_3Layout = new javax.swing.GroupLayout(jPanel_3);
        jPanel_3.setLayout(jPanel_3Layout);
        jPanel_3Layout.setHorizontalGroup(
            jPanel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_3Layout.setVerticalGroup(
            jPanel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_3Layout.createSequentialGroup()
                .addComponent(jPanel3_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        jPanel_5.setBackground(new java.awt.Color(51, 198, 75));

        jPanel5_Header.setBackground(new java.awt.Color(51, 231, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Lastest Books");

        javax.swing.GroupLayout jPanel5_HeaderLayout = new javax.swing.GroupLayout(jPanel5_Header);
        jPanel5_Header.setLayout(jPanel5_HeaderLayout);
        jPanel5_HeaderLayout.setHorizontalGroup(
            jPanel5_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5_HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5_HeaderLayout.setVerticalGroup(
            jPanel5_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Image_2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Image_2.setOpaque(true);

        jLabel_Image_3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Image_3.setOpaque(true);

        jLabel_Image_4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Image_4.setOpaque(true);

        jLabel_Image_5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Image_5.setOpaque(true);

        jLabel_Image_1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_Image_1.setOpaque(true);

        javax.swing.GroupLayout jPanel_5Layout = new javax.swing.GroupLayout(jPanel_5);
        jPanel_5.setLayout(jPanel_5Layout);
        jPanel_5Layout.setHorizontalGroup(
            jPanel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_Image_1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel_Image_2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel_Image_3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel_Image_4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel_Image_5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_5Layout.setVerticalGroup(
            jPanel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_5Layout.createSequentialGroup()
                .addComponent(jPanel5_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Image_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_3, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        jLabel_Welcome_UserName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_Welcome_UserName.setText("Welcome back: UserName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                    .addComponent(jPanel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jPanel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Welcome_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel_1, jPanel_2, jPanel_3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 692, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Welcome_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(jPanel_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel_1, jPanel_2, jPanel_3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ManagerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ManagerUserActionPerformed
        //show the manager users form (show only for user role : OWNER)
        ManageUserForm manageUserForm = new ManageUserForm();
        manageUserForm.setVisible(true);
    }//GEN-LAST:event_jButton_ManagerUserActionPerformed

    private void jButton_BookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BookListActionPerformed
        BookListForm bookListForm = new BookListForm();
        bookListForm.setVisible(true);
    }//GEN-LAST:event_jButton_BookListActionPerformed

    private void jButton_Delete_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_BookActionPerformed
        DeleteBookForm deleteBookForm = new DeleteBookForm();
        deleteBookForm.setVisible(true);
    }//GEN-LAST:event_jButton_Delete_BookActionPerformed

    private void jButton_Edit_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_BookActionPerformed
        EditBookForm editBookForm = new EditBookForm();
        editBookForm.setVisible(true);
    }//GEN-LAST:event_jButton_Edit_BookActionPerformed

    private void jButton_Add_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_BookActionPerformed
        AddBookForm addBookForm = new AddBookForm();
        addBookForm.setVisible(true);
    }//GEN-LAST:event_jButton_Add_BookActionPerformed

    private void jButton_MembersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MembersListActionPerformed
        MembersListForm membersListForm = new MembersListForm();
        membersListForm.setVisible(true);
    }//GEN-LAST:event_jButton_MembersListActionPerformed

    private void jButton_Delete_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_MemberActionPerformed
        DeleteMemberForm deleteMemberForm = new DeleteMemberForm();
        deleteMemberForm.setVisible(true);
    }//GEN-LAST:event_jButton_Delete_MemberActionPerformed

    private void jButton_Add_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_MemberActionPerformed
        AddMemberForm addMemberForm = new AddMemberForm();
        addMemberForm.setVisible(true);
    }//GEN-LAST:event_jButton_Add_MemberActionPerformed

    private void jButton_Edit_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_MemberActionPerformed
        EditMemberForm editMemberForm = new EditMemberForm();
        editMemberForm.setVisible(true);
    }//GEN-LAST:event_jButton_Edit_MemberActionPerformed

    private void jButton_Manager_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Manager_AuthorActionPerformed
        ManageAuthorForm manageAuthorForm = new ManageAuthorForm();
        manageAuthorForm.setVisible(true);
    }//GEN-LAST:event_jButton_Manager_AuthorActionPerformed

    private void jButton_Manager_GenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Manager_GenresActionPerformed
        ManageGenresForm manageGenresForm = new ManageGenresForm();
        manageGenresForm.setVisible(true);
    }//GEN-LAST:event_jButton_Manager_GenresActionPerformed

    private void jButton_Return_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Return_BookActionPerformed
        ReturnBookForm returnBookForm = new ReturnBookForm();
        returnBookForm.setVisible(true);
    }//GEN-LAST:event_jButton_Return_BookActionPerformed

    private void jButton_Issue_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Issue_BookActionPerformed
        IssueBookForm issueBookForm = new IssueBookForm();
        issueBookForm.setVisible(true);
    }//GEN-LAST:event_jButton_Issue_BookActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Book;
    private javax.swing.JButton jButton_Add_Member;
    private javax.swing.JButton jButton_BookList;
    private javax.swing.JButton jButton_Delete_Book;
    private javax.swing.JButton jButton_Delete_Member;
    private javax.swing.JButton jButton_Edit_Book;
    private javax.swing.JButton jButton_Edit_Member;
    public javax.swing.JButton jButton_Issue_Book;
    public javax.swing.JButton jButton_ManagerUser;
    private javax.swing.JButton jButton_Manager_Author;
    private javax.swing.JButton jButton_Manager_Genres;
    private javax.swing.JButton jButton_MembersList;
    public javax.swing.JButton jButton_Return_Book;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Book_Count;
    public javax.swing.JLabel jLabel_CanLe;
    public javax.swing.JLabel jLabel_Circulation;
    private javax.swing.JLabel jLabel_DashBoard_Logo;
    private javax.swing.JLabel jLabel_DashBoard_Text;
    private javax.swing.JLabel jLabel_Image_1;
    private javax.swing.JLabel jLabel_Image_2;
    private javax.swing.JLabel jLabel_Image_3;
    private javax.swing.JLabel jLabel_Image_4;
    private javax.swing.JLabel jLabel_Image_5;
    private javax.swing.JLabel jLabel_Members_Count;
    public javax.swing.JLabel jLabel_Welcome_UserName;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1_Header;
    private javax.swing.JPanel jPanel2_Header;
    private javax.swing.JPanel jPanel3_Header;
    private javax.swing.JPanel jPanel5_Header;
    private javax.swing.JPanel jPanel_1;
    private javax.swing.JPanel jPanel_2;
    private javax.swing.JPanel jPanel_3;
    private javax.swing.JPanel jPanel_5;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JPanel jPanel_Menu;
    private javaswingdev.swing.titlebar.TitleBar titleBar;
    // End of variables declaration//GEN-END:variables
}
