package My_Forms;

import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Nguyễn Văn Khoa
 */
public class EditBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    My_Classes.Book book = new My_Classes.Book();
    My_Classes.Member member = new My_Classes.Member();
    My_Classes.Author author = new My_Classes.Author();
    My_Classes.Func_Class func = new My_Classes.Func_Class();
    My_Classes.Genres genre = new My_Classes.Genres();
    HashMap<String, Integer> genHashMap = genre.getGenresMap();

    String imagePath = "";

    public EditBookForm() {
        initComponents();
        this.setLocationRelativeTo(null);

        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(102, 102, 102));
        jPanel1.setBorder(panelHeaderBorder);

        //display image title   
        func.displayImage(80, 80, null, "/My_Images/icons8_book_reading_100px.png", jLabel_Form_Title);

        //add black border for the jlable image
        Border panelImageBorder = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        jLabel_Image1.setBorder(panelImageBorder);

        //populate jcombobox with genres
        fillJComboboxWithGenres();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_FirstName = new javax.swing.JLabel();
        jTextField_ISBN = new javax.swing.JTextField();
        jLabel_FirstName1 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLabel_FirstName2 = new javax.swing.JLabel();
        jTextField_Author = new javax.swing.JTextField();
        jLabel_FirstName3 = new javax.swing.JLabel();
        jLabel_FirstName4 = new javax.swing.JLabel();
        jTextField_Publisher = new javax.swing.JTextField();
        jLabel_FirstName5 = new javax.swing.JLabel();
        jTextField_Price = new javax.swing.JTextField();
        jLabel_FirstName6 = new javax.swing.JLabel();
        jLabel_FirstName7 = new javax.swing.JLabel();
        jLabel_FirstName8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_Book_Description = new javax.swing.JTextField();
        jLabel_FirstName9 = new javax.swing.JLabel();
        jLabel_Image1 = new javax.swing.JLabel();
        jLabel_ImagePath = new javax.swing.JLabel();
        jButton_Select_Picture = new javax.swing.JButton();
        jButton_Cancle = new javax.swing.JButton();
        jButton_Edit_Book = new javax.swing.JButton();
        jComboBox_Genre = new javax.swing.JComboBox<>();
        jSpinner_Quanlity = new javax.swing.JSpinner();
        jDateChooser_DateRecived = new com.toedter.calendar.JDateChooser();
        jButton_Select_Author = new javax.swing.JButton();
        jLabel_ID_Author = new javax.swing.JLabel();
        jLabel_ID_Genre = new javax.swing.JLabel();
        jButton_Clear_Books = new javax.swing.JButton();
        jLabel_FirstName10 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Form_Title.setBackground(new java.awt.Color(0, 70, 106));
        jLabel_Form_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(255, 115, 10));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("Edit A Book");
        jLabel_Form_Title.setOpaque(true);

        jLabel_Close.setBackground(new java.awt.Color(0, 70, 106));
        jLabel_Close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.setOpaque(true);
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName.setText("ISBN:");

        jTextField_ISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_FirstName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName1.setText("Name:");

        jTextField_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jLabel_FirstName2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName2.setText("Author:");

        jTextField_Author.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Author.setEnabled(false);

        jLabel_FirstName3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName3.setText("Genre:");

        jLabel_FirstName4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName4.setText("Quanlity:");

        jTextField_Publisher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_FirstName5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName5.setText("Publisher:");

        jTextField_Price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_FirstName6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName6.setText("Price:");

        jLabel_FirstName7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName7.setText("Date Recived:");

        jLabel_FirstName8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName8.setText("Book Description:");

        jTextField_Book_Description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField_Book_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField_Book_Description, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        jLabel_FirstName9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName9.setText("Book Cover:");

        jLabel_Image1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image1.setOpaque(true);

        jLabel_ImagePath.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel_ImagePath.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_ImagePath.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_ImagePath.setText("picture path...");

        jButton_Select_Picture.setBackground(new java.awt.Color(153, 0, 153));
        jButton_Select_Picture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Select_Picture.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Select_Picture.setText("Select Picture");
        jButton_Select_Picture.setContentAreaFilled(false);
        jButton_Select_Picture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Select_Picture.setOpaque(true);
        jButton_Select_Picture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_PictureActionPerformed(evt);
            }
        });

        jButton_Cancle.setBackground(new java.awt.Color(0, 70, 106));
        jButton_Cancle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Cancle.setForeground(new java.awt.Color(255, 115, 10));
        jButton_Cancle.setText("CANCEL");
        jButton_Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancleActionPerformed(evt);
            }
        });

        jButton_Edit_Book.setBackground(new java.awt.Color(0, 70, 106));
        jButton_Edit_Book.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Edit_Book.setForeground(new java.awt.Color(255, 115, 10));
        jButton_Edit_Book.setText("EDIT BOOK");
        jButton_Edit_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_BookActionPerformed(evt);
            }
        });

        jComboBox_Genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_GenreActionPerformed(evt);
            }
        });

        jButton_Select_Author.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Select_Author.setText("Change Author");
        jButton_Select_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_AuthorActionPerformed(evt);
            }
        });

        jLabel_ID_Author.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_ID_Author.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_ID_Author.setText("ID");

        jLabel_ID_Genre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_ID_Genre.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_ID_Genre.setText("ID");

        jButton_Clear_Books.setBackground(new java.awt.Color(0, 70, 106));
        jButton_Clear_Books.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Clear_Books.setForeground(new java.awt.Color(255, 115, 10));
        jButton_Clear_Books.setText("CLEAR");
        jButton_Clear_Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Clear_BooksActionPerformed(evt);
            }
        });

        jLabel_FirstName10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName10.setText("ID:");

        jTextField_ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton_Search.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Search.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton_Search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Search.setText("Search by id or isbn");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton_Clear_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Edit_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jButton_Cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_FirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Genre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_FirstName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ID_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_ID_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Select_Author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName7)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser_DateRecived, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Price))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Publisher))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner_Quanlity))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_FirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_FirstName10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_FirstName8)
                            .addComponent(jLabel_FirstName9)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Select_Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(75, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_FirstName8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel_FirstName9)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_ImagePath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Select_Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_FirstName10)
                                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_FirstName)
                                    .addComponent(jTextField_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName1)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName2)
                            .addComponent(jTextField_Author, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jButton_Select_Author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ID_Author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName3)
                            .addComponent(jComboBox_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ID_Genre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName4)
                            .addComponent(jSpinner_Quanlity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName5)
                            .addComponent(jTextField_Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName6)
                            .addComponent(jTextField_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_FirstName7)
                            .addComponent(jDateChooser_DateRecived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancle)
                    .addComponent(jButton_Edit_Book)
                    .addComponent(jButton_Clear_Books))
                .addGap(31, 31, 31))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox_Genre, jSpinner_Quanlity, jTextField_Author, jTextField_ID, jTextField_ISBN, jTextField_Name, jTextField_Price, jTextField_Publisher});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jButton_Select_PictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_PictureActionPerformed
        //select pictuer from the PC

        String path = func.selectImage();
        jLabel_ImagePath.setText(path);

        //display the image when we select in path
        func.displayImage(240, 177, null, path, jLabel_Image1);

        imagePath = path;
    }//GEN-LAST:event_jButton_Select_PictureActionPerformed

    private void jButton_CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancleActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancleActionPerformed

    private void jButton_Edit_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_BookActionPerformed

        //edit a  Book
        //we will not eidt the isbn

        if (!verif()) {
            JOptionPane.showMessageDialog(null, "One Or More Fields Is Empty", "empty data", 2);
        } else {
            try {
                int id = Integer.parseInt(jTextField_ID.getText());
                String name = jTextField_Name.getText();
                String publisher = jTextField_Publisher.getText();
                String desciption = jTextField_Book_Description.getText();

                Integer author_id = Integer.parseInt(jLabel_ID_Author.getText());   //get the id author
                Integer genre_id = Integer.parseInt(jLabel_ID_Genre.getText());     //get the id genre
                Integer quanlity = Integer.parseInt(jSpinner_Quanlity.getValue().toString());

                double price = Double.parseDouble(jTextField_Price.getText());

                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String received_Date = dateFormat.format(jDateChooser_DateRecived.getDate());
                Path path = Paths.get(imagePath);

                try {
                    //if the user want to change the image
                    byte[] img = Files.readAllBytes(path);
                    book.editBook(id, name, author_id, genre_id, quanlity, publisher, price, received_Date, desciption, img);
                } catch (IOException e) {   //if not want to change
                    book.editBook(id, name, author_id, genre_id, quanlity, publisher, price, received_Date, desciption, null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(EditBookForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "You Enterred Wrong Data In A Number Field", "Wrong data number", 2);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "You Need To Select A Date", "Select date", 2);
            }
        }

    }//GEN-LAST:event_jButton_Edit_BookActionPerformed

    private void jButton_Select_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_AuthorActionPerformed
        //show a form 
        //the form will have a jtable populated with author
        //the user can select the author from the table and it will displayed in the jtextfield
        AuthorListForm authorListForm = new AuthorListForm();
        authorListForm.formType = "edit";
        authorListForm.setVisible(true);
    }//GEN-LAST:event_jButton_Select_AuthorActionPerformed

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jComboBox_GenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_GenreActionPerformed
        //display the selectedbook genre id:
        //if the combobox is empty an error will be throw
        //so, to avoid that, we will add a empty try catch just an case
        try {
            int genreId = genHashMap.get(jComboBox_Genre.getSelectedItem().toString());
            jLabel_ID_Genre.setText(String.valueOf(genreId));
        } catch (Exception e) {
            System.out.println("Eror from Jcombobox_Genre_ActionPerformed - " + e.getMessage());
        }
    }//GEN-LAST:event_jComboBox_GenreActionPerformed

    private void jButton_Clear_BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Clear_BooksActionPerformed
        jTextField_ID.setText("");
        jTextField_ISBN.setText("");
        jTextField_Name.setText("");
        jTextField_Price.setText("");
        jTextField_Author.setText("");
        jTextField_Publisher.setText("");
        jSpinner_Quanlity.setValue(0);
        jDateChooser_DateRecived.setDate(new Date());
        jTextField_Book_Description.setText("");
        jComboBox_Genre.setSelectedIndex(0);
        jLabel_Image1.setIcon(null);
        jLabel_ImagePath.setText("picture path...");
    }//GEN-LAST:event_jButton_Clear_BooksActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        //check if the id fields or the isbn are empty
        if (jTextField_ID.getText().equals("") && jTextField_ISBN.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You Need To Enter The ID Or the ISBN To Complete The Search ", "Empty ID or ISBN", 2);
        } else {
            try {
                //search book by id or isbn:
                My_Classes.Book selectedbook;

                int id = 0;
                id = Integer.parseInt(jTextField_ID.getText());
                String isbn = jTextField_ISBN.getText();
                selectedbook = book.searchBook(id, isbn);

                if (selectedbook != null) {
                    jTextField_ID.setText(String.valueOf(selectedbook.getBook_id()));
                    jTextField_ISBN.setText(selectedbook.getIsbn());
                    jTextField_Name.setText(selectedbook.getName());
                    jTextField_Publisher.setText(selectedbook.getPublisher());
                    jSpinner_Quanlity.setValue(selectedbook.getQuanlity());
                    jTextField_Price.setText(Double.toString(selectedbook.getPrice()));
                    jTextField_Book_Description.setText(selectedbook.getDescription());
                    jLabel_ID_Author.setText(String.valueOf(selectedbook.getAuthor_id()));
                    jLabel_ID_Genre.setText(String.valueOf(selectedbook.getGenre_id()));

                    //display the author full name
                    String fullname = (author.getAuthorByID(selectedbook.getAuthor_id())).getFirstName()
                            + " " + (author.getAuthorByID(selectedbook.getAuthor_id())).getLastName();
                    jTextField_Author.setText(fullname);

                    //display the selected book genre in the jcombobox
                    for (Map.Entry<String, Integer> entry : genHashMap.entrySet()) {
                        if (Objects.equals(selectedbook.getGenre_id(), entry.getValue())) {
                            jComboBox_Genre.setSelectedItem(entry.getKey());
                        }
                    }

                    //display the date
                    Date date_recieved = new SimpleDateFormat("yyyy-MM-dd").parse(selectedbook.getDate_received());
                    jDateChooser_DateRecived.setDate(date_recieved);

                    //display image:
                    byte[] image = selectedbook.getCover();
                    //we will display the image using the imagebyte
                    //so we will made the image path null
                    func.displayImage(238, 177, image, "", jLabel_Image1);
                } else {
                    JOptionPane.showMessageDialog(null, "No Books With This ID Found", "invalid id book", 2);
                }
            } catch (SQLException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "This Book Does Not Exist " + ex.getMessage(), "Book not found", 2);
            } catch (ParseException ex) {
                Logger.getLogger(EditBookForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton_SearchActionPerformed

    //display author in the jtextfield_author by id and fullname
    public static void displayAuthorData(int id, String fullName) {
        jTextField_Author.setText(fullName);
        jLabel_ID_Author.setText(String.valueOf(id));

    }

    //creat a function to populate the jcombobox with the genre name and id using hashmap
    public void fillJComboboxWithGenres() {
        for (String genreName : genHashMap.keySet()) {
            jComboBox_Genre.addItem(genreName);
        }
    }

    //creat a function to verify the required fields
    public boolean verif() {
        if (jTextField_ISBN.getText().equals("") || jTextField_Author.getText().equals("")
                || jTextField_Price.getText().equals("") || jTextField_Name.getText().equals("")
                || jLabel_ID_Genre.getText().equals("ID")) {
            return false;
        } else {
            return true;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancle;
    private javax.swing.JButton jButton_Clear_Books;
    private javax.swing.JButton jButton_Edit_Book;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Select_Author;
    private javax.swing.JButton jButton_Select_Picture;
    private javax.swing.JComboBox<String> jComboBox_Genre;
    private com.toedter.calendar.JDateChooser jDateChooser_DateRecived;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_FirstName1;
    private javax.swing.JLabel jLabel_FirstName10;
    private javax.swing.JLabel jLabel_FirstName2;
    private javax.swing.JLabel jLabel_FirstName3;
    private javax.swing.JLabel jLabel_FirstName4;
    private javax.swing.JLabel jLabel_FirstName5;
    private javax.swing.JLabel jLabel_FirstName6;
    private javax.swing.JLabel jLabel_FirstName7;
    private javax.swing.JLabel jLabel_FirstName8;
    private javax.swing.JLabel jLabel_FirstName9;
    private javax.swing.JLabel jLabel_Form_Title;
    private static javax.swing.JLabel jLabel_ID_Author;
    private javax.swing.JLabel jLabel_ID_Genre;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Image1;
    private javax.swing.JLabel jLabel_ImagePath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner_Quanlity;
    private static javax.swing.JTextField jTextField_Author;
    private javax.swing.JTextField jTextField_Book_Description;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_ISBN;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Price;
    private javax.swing.JTextField jTextField_Publisher;
    // End of variables declaration//GEN-END:variables
}
