package My_Forms;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Nguyễn Văn Khoa
 */
public class IssueBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    My_Classes.Member member = new My_Classes.Member();
    My_Classes.Func_Class func = new My_Classes.Func_Class();
    My_Classes.Book book = new My_Classes.Book();
    My_Classes.Issue_Book issueBook = new My_Classes.Issue_Book();

    boolean book_Exist = false;
    boolean mem_Exist = false;

    public IssueBookForm() {
        initComponents();
        this.setLocationRelativeTo(null);

        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(53, 53, 55));
        jPanel1.setBorder(panelHeaderBorder);

        //display image title   
        func.displayImage(80, 80, null, "/My_Images/icons8_book_100px_2.png", jLabel_Form_Title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_FirstName1 = new javax.swing.JLabel();
        jButton_Cancle = new javax.swing.JButton();
        jButton_issue_Book = new javax.swing.JButton();
        jButton_Select_Member = new javax.swing.JButton();
        jButton_Select_Book = new javax.swing.JButton();
        jLabel_MemberName = new javax.swing.JLabel();
        jLabel_Bookname = new javax.swing.JLabel();
        jLabel_FirstName2 = new javax.swing.JLabel();
        jLabel_Available = new javax.swing.JLabel();
        jLabel_FirstName7 = new javax.swing.JLabel();
        jDateChooser_Issue_Date = new com.toedter.calendar.JDateChooser();
        jLabel_FirstName8 = new javax.swing.JLabel();
        jDateChooser_ReturnDate = new com.toedter.calendar.JDateChooser();
        jSpinner_MemberID = new javax.swing.JSpinner();
        jSpinner_IDBook = new javax.swing.JSpinner();
        jLabel_FirstName9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Form_Title.setBackground(new java.awt.Color(53, 53, 55));
        jLabel_Form_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(109, 180, 50));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("Issue Book");
        jLabel_Form_Title.setOpaque(true);

        jLabel_Close.setBackground(new java.awt.Color(53, 53, 55));
        jLabel_Close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.setOpaque(true);
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName.setText("Enter Book ID:");

        jLabel_FirstName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName1.setText("Enter Member ID:");

        jButton_Cancle.setBackground(new java.awt.Color(53, 53, 55));
        jButton_Cancle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Cancle.setForeground(new java.awt.Color(109, 180, 50));
        jButton_Cancle.setText("CANCEL");
        jButton_Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancleActionPerformed(evt);
            }
        });

        jButton_issue_Book.setBackground(new java.awt.Color(53, 53, 55));
        jButton_issue_Book.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_issue_Book.setForeground(new java.awt.Color(109, 180, 50));
        jButton_issue_Book.setText("ISSUE BOOK");
        jButton_issue_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_issue_BookActionPerformed(evt);
            }
        });

        jButton_Select_Member.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Select_Member.setText("Search Member");
        jButton_Select_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_MemberActionPerformed(evt);
            }
        });

        jButton_Select_Book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Select_Book.setText("Search Book");
        jButton_Select_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_BookActionPerformed(evt);
            }
        });

        jLabel_MemberName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_MemberName.setForeground(new java.awt.Color(139, 192, 100));
        jLabel_MemberName.setText("Member Full Name");
        jLabel_MemberName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MemberNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MemberNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MemberNameMouseExited(evt);
            }
        });

        jLabel_Bookname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_Bookname.setForeground(new java.awt.Color(139, 192, 100));
        jLabel_Bookname.setText("Book Name");
        jLabel_Bookname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BooknameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_BooknameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_BooknameMouseExited(evt);
            }
        });

        jLabel_FirstName2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName2.setText("Is Book Available:");

        jLabel_Available.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel_Available.setForeground(new java.awt.Color(139, 192, 100));
        jLabel_Available.setText("YES - NO");

        jLabel_FirstName7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName7.setText("Issue Date:");

        jLabel_FirstName8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName8.setText("Return Date:");

        jSpinner_MemberID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jSpinner_IDBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel_FirstName9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName9.setText("Note:");

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton_issue_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton_Cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_FirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel_Available, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_FirstName8)
                                            .addComponent(jLabel_FirstName7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDateChooser_Issue_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                            .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_FirstName9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_MemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel_FirstName))
                                    .addComponent(jLabel_FirstName1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Bookname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinner_MemberID, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(jSpinner_IDBook, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Select_Member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Select_Book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner_IDBook, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Select_Book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Bookname)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Select_Member, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jSpinner_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_MemberName)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FirstName2)
                    .addComponent(jLabel_Available))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_Issue_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_FirstName7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_FirstName8))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_FirstName9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_issue_Book)
                    .addComponent(jButton_Cancle))
                .addGap(52, 52, 52))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSpinner_IDBook, jSpinner_MemberID});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_issue_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_issue_BookActionPerformed

        try {
            int _book_id = (int) jSpinner_IDBook.getValue();
            int _member_id = (int) jSpinner_MemberID.getValue();
            String _note = jTextArea_Note.getText();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String _Issue_Date = dateFormat.format(jDateChooser_Issue_Date.getDate());
            String _Return_Date = dateFormat.format(jDateChooser_ReturnDate.getDate());

            //before issuing a book we need to check
            //if the return date came the issue date
            Date issDate = dateFormat.parse(_Issue_Date);
            Date reDate = dateFormat.parse(_Return_Date);

            //we nedd to check if the book add member exits
            if (!book_Exist) {
                JOptionPane.showMessageDialog(null, "You Need To Check If This Book Exist First By Click Search Button", "Check the book exist", 2);
            } else if (!mem_Exist) {
                JOptionPane.showMessageDialog(null, "You Need To Check If This Member Exist First By Click Search Button", "Check the member exist", 2);
            } //we need to check if the book avaible
            else if (!issueBook.checkBookAvailability(_book_id)) {
                JOptionPane.showMessageDialog(null, "This Book Is Not Available Right Now", "Book not available", 2);
            } else if (reDate.before(issDate)) {
                JOptionPane.showMessageDialog(null, "The Return Date Must Be After The Issue Date", "Wrong Date", 2);
            } else {
                issueBook.addIssue(_book_id, _member_id, _note, _Issue_Date, _Return_Date, _note);
                jSpinner_IDBook.setValue(0);
                jSpinner_MemberID.setValue(0);
                jLabel_Bookname.setText("Book Name");
                jLabel_MemberName.setText("Member Full Name");
                jLabel_Available.setText("YES - NO");
                jTextArea_Note.setText("");
                jDateChooser_Issue_Date.setDate(new Date());
                jDateChooser_ReturnDate.setDate(new Date());
                book_Exist = false;
                mem_Exist = false;

            }

        } catch (SQLException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "You Need To Select A Date Issue & Date Return", "Select date", 2);
        } catch (ParseException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_issue_BookActionPerformed

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jButton_CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancleActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancleActionPerformed

    private void jButton_Select_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_MemberActionPerformed
        //search member by id and display his full name:
        int member_id = (int) jSpinner_MemberID.getValue();

        try {
            //get the book id
            My_Classes.Member selectedMember = member.getMemberById(member_id);

            if (selectedMember != null) {
                //display the book title 
                jLabel_MemberName.setText(String.valueOf(selectedMember.getFirstName()) + " " + selectedMember.getLastName());
                //set the member exist to true
                mem_Exist = true;
            } else {
                JOptionPane.showMessageDialog(null, "THIS MEMBER ID DOESN'T EXIST", "Member not found", 2);
                jLabel_MemberName.setText("Member Full Name");
                mem_Exist = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Select_MemberActionPerformed

    private void jButton_Select_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_BookActionPerformed
        //search for the book by ID
        //display the book title
        //check if this book is avalble or not
        int book_id = (int) jSpinner_IDBook.getValue();

        try {
            //get the book id
            My_Classes.Book selectedBook = book.getBookById(book_id);

            if (selectedBook != null) {
                //display the book title 
                jLabel_Bookname.setText(String.valueOf(selectedBook.getName()));
                //set the book exist to true
                book_Exist = true;

                //display the avaiblality
                if (issueBook.checkBookAvailability(book_id)) {
                    jLabel_Available.setText("YES");
                    jLabel_Available.setForeground(new Color(139, 192, 100));
                } else {
                    jLabel_Available.setText("NO");
                    jLabel_Available.setForeground(Color.red);
                }
            } else {
                jLabel_Bookname.setText("Book Name");
                JOptionPane.showMessageDialog(null, "THIS ID BOOK DOESN'T EXIST", "Book not found", 2);
                book_Exist = false;
                jLabel_Available.setText("YES - NO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Select_BookActionPerformed

    private void jLabel_BooknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BooknameMouseClicked
        int book_id = (int) jSpinner_IDBook.getValue();
        BookInforCardForm bookInforCardForm = new BookInforCardForm(book_id);
        bookInforCardForm.setVisible(true);
    }//GEN-LAST:event_jLabel_BooknameMouseClicked

    private void jLabel_MemberNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberNameMouseClicked
        int mem_id = (int) jSpinner_MemberID.getValue();
        MemberInforCardForm memberInforCardForm = new MemberInforCardForm(mem_id);
        memberInforCardForm.setVisible(true);
    }//GEN-LAST:event_jLabel_MemberNameMouseClicked

    private void jLabel_BooknameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BooknameMouseEntered
        //add aborder in the bottom of the book name jlable
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(139, 192, 100));
        jLabel_Bookname.setBorder(border);
    }//GEN-LAST:event_jLabel_BooknameMouseEntered

    private void jLabel_BooknameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BooknameMouseExited
        //add aborder in the bottom of the book name jlable
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255, 255, 255));
        jLabel_Bookname.setBorder(border);
    }//GEN-LAST:event_jLabel_BooknameMouseExited

    private void jLabel_MemberNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberNameMouseEntered
        //add aborder in the bottom of the book name jlable
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(139, 192, 100));
        jLabel_MemberName.setBorder(border);
    }//GEN-LAST:event_jLabel_MemberNameMouseEntered

    private void jLabel_MemberNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberNameMouseExited
        //add aborder in the bottom of the book name jlable
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255, 255, 255));
        jLabel_MemberName.setBorder(border);
    }//GEN-LAST:event_jLabel_MemberNameMouseExited

    //creat a function to verify the required fields
    public boolean verif() {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancle;
    private javax.swing.JButton jButton_Select_Book;
    private javax.swing.JButton jButton_Select_Member;
    private javax.swing.JButton jButton_issue_Book;
    private com.toedter.calendar.JDateChooser jDateChooser_Issue_Date;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate;
    private javax.swing.JLabel jLabel_Available;
    private javax.swing.JLabel jLabel_Bookname;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_FirstName1;
    private javax.swing.JLabel jLabel_FirstName2;
    private javax.swing.JLabel jLabel_FirstName7;
    private javax.swing.JLabel jLabel_FirstName8;
    private javax.swing.JLabel jLabel_FirstName9;
    private javax.swing.JLabel jLabel_Form_Title;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_MemberName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_IDBook;
    private javax.swing.JSpinner jSpinner_MemberID;
    private javax.swing.JTextArea jTextArea_Note;
    // End of variables declaration//GEN-END:variables
}
