package My_Forms;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyễn Văn Khoa
 */
public class ReturnBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    My_Classes.Member member = new My_Classes.Member();
    My_Classes.Func_Class func = new My_Classes.Func_Class();
    My_Classes.Book book = new My_Classes.Book();
    My_Classes.Issue_Book issueBook = new My_Classes.Issue_Book();

    boolean book_Exist = false;
    boolean mem_Exist = false;

    public ReturnBookForm() {
        initComponents();
        this.setLocationRelativeTo(null);

        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(53, 53, 55));
        jPanel1.setBorder(panelHeaderBorder);

        //display image title   
        func.displayImage(80, 80, null, "/My_Images/icons8_book_100px_2.png", jLabel_Form_Title);

        //custon the table
        func.customTable(jTable_IssueBook);

        //custom the headertable
        func.customTableHeader(jTable_IssueBook, new Color(204, 132, 0), 13);

        //diplay the table
        populateJtableWithissueBooks("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_FirstName1 = new javax.swing.JLabel();
        jButton_Lost = new javax.swing.JButton();
        jButton_Return_Book = new javax.swing.JButton();
        jButton_Select_Member = new javax.swing.JButton();
        jButton_Select_Book = new javax.swing.JButton();
        jLabel_MemberName = new javax.swing.JLabel();
        jLabel_Bookname = new javax.swing.JLabel();
        jLabel_FirstName7 = new javax.swing.JLabel();
        jDateChooser_Issue_Date = new com.toedter.calendar.JDateChooser();
        jLabel_FirstName8 = new javax.swing.JLabel();
        jDateChooser_ReturnDate = new com.toedter.calendar.JDateChooser();
        jSpinner_MemberID = new javax.swing.JSpinner();
        jSpinner_IDBook = new javax.swing.JSpinner();
        jLabel_FirstName9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_IssueBook = new javax.swing.JTable();
        jLabel_FirstName2 = new javax.swing.JLabel();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jButton_Delete_Book = new javax.swing.JButton();

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Form_Title.setBackground(new java.awt.Color(51, 0, 153));
        jLabel_Form_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(204, 132, 0));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("Return Book");
        jLabel_Form_Title.setOpaque(true);

        jLabel_Close.setBackground(new java.awt.Color(51, 0, 153));
        jLabel_Close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.setOpaque(true);
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName.setText("Book ID:");

        jLabel_FirstName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName1.setText("Member ID:");

        jButton_Lost.setBackground(new java.awt.Color(51, 0, 153));
        jButton_Lost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Lost.setForeground(new java.awt.Color(204, 132, 0));
        jButton_Lost.setText("LOST");
        jButton_Lost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LostActionPerformed(evt);
            }
        });

        jButton_Return_Book.setBackground(new java.awt.Color(51, 0, 153));
        jButton_Return_Book.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Return_Book.setForeground(new java.awt.Color(204, 132, 0));
        jButton_Return_Book.setText("RETURN BOOK");
        jButton_Return_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Return_BookActionPerformed(evt);
            }
        });

        jButton_Select_Member.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Select_Member.setText("Search Member");
        jButton_Select_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_MemberActionPerformed(evt);
            }
        });

        jButton_Select_Book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Select_Book.setText("Search Book");
        jButton_Select_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_BookActionPerformed(evt);
            }
        });

        jLabel_MemberName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_MemberName.setForeground(new java.awt.Color(204, 132, 0));
        jLabel_MemberName.setText("Member Full Name");
        jLabel_MemberName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MemberNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MemberNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MemberNameMouseExited(evt);
            }
        });

        jLabel_Bookname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_Bookname.setForeground(new java.awt.Color(204, 132, 0));
        jLabel_Bookname.setText("Book Name");
        jLabel_Bookname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BooknameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_BooknameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_BooknameMouseExited(evt);
            }
        });

        jLabel_FirstName7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName7.setText("Issue Date:");

        jLabel_FirstName8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName8.setText("Return Date:");

        jSpinner_MemberID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jSpinner_IDBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel_FirstName9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName9.setText("Note:");

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note);

        jTable_IssueBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_IssueBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_IssueBook.setAutoscrolls(false);
        jTable_IssueBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_IssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_IssueBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_IssueBook);

        jLabel_FirstName2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_FirstName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_FirstName2.setText("Select Book Status:");

        jComboBox_Status.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Issued", "Returned", "Lost" }));
        jComboBox_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_StatusActionPerformed(evt);
            }
        });

        jButton_Delete_Book.setBackground(new java.awt.Color(51, 0, 153));
        jButton_Delete_Book.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Delete_Book.setForeground(new java.awt.Color(204, 132, 0));
        jButton_Delete_Book.setText("DELETE BOOK");
        jButton_Delete_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_BookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_MemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel_FirstName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel_Bookname, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                                    .addComponent(jSpinner_MemberID)
                                                    .addComponent(jSpinner_IDBook))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton_Select_Member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_Select_Book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_FirstName8)
                                            .addComponent(jLabel_FirstName7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_FirstName9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jDateChooser_Issue_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                                .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_Return_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(jButton_Lost, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Delete_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_Lost, jButton_Return_Book});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner_IDBook, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Select_Book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_FirstName2)
                        .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Bookname)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Select_Member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_MemberName)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_Issue_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_FirstName7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_FirstName8))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_FirstName9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Return_Book, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(jButton_Lost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Delete_Book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSpinner_IDBook, jSpinner_MemberID});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Return_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Return_BookActionPerformed

        //return a book
        //we will update the return date
        //the note
        //and the status to returned
        //NOTE: if you change a book status from LOST to RETURN you need to update the quanlity
        //or you can prevent the user from changing the status when it's set to lost
        try {
            int _book_id = (int) jSpinner_IDBook.getValue();
            int _member_id = (int) jSpinner_MemberID.getValue();
            String _note = jTextArea_Note.getText();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String _Issue_Date = dateFormat.format(jDateChooser_Issue_Date.getDate());
            String _Return_Date = dateFormat.format(jDateChooser_ReturnDate.getDate());

            Date issDate = dateFormat.parse(_Issue_Date);
            Date reDate = dateFormat.parse(_Return_Date);

            if (reDate.before(issDate)) {
                JOptionPane.showMessageDialog(null, "The Return Date Must Be After The Issue Date", "Wrong Date", 2);
            } else {
                issueBook.updateIssue(_book_id, _member_id, "Returned", _Issue_Date, _Issue_Date, _note);
                jSpinner_IDBook.setValue(0);
                jSpinner_MemberID.setValue(0);
                jLabel_Bookname.setText("Book Name");
                jLabel_MemberName.setText("Member Full Name");
                jTextArea_Note.setText("");
                jDateChooser_Issue_Date.setDate(new Date());
                jDateChooser_ReturnDate.setDate(new Date());
                jTextArea_Note.setText("");
            }
            populateJtableWithissueBooks("");
        } catch (SQLException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Select An Item From The Table", "Select item", 2);
        } catch (ParseException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_Return_BookActionPerformed

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jButton_LostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LostActionPerformed
        //the book is lost 
        //we need to the book status to lost
        //and update the book quanlity
        //the new quanlity = the quanlity - 1
        //even if the book is lost we will not change the return date 

        try {
            int _book_id = (int) jSpinner_IDBook.getValue();
            int _member_id = (int) jSpinner_MemberID.getValue();
            String _note = jTextArea_Note.getText();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

            String _Issue_Date = dateFormat.format(jDateChooser_Issue_Date.getDate());
            String _Return_Date = dateFormat.format(jDateChooser_ReturnDate.getDate());

            issueBook.updateIssue(_book_id, _member_id, "Lost", _Issue_Date, _Issue_Date, _note);

            //now we need to update the book quanlity (quanlity - 1)
            int quanlity = new My_Classes.Book().getBookById(_book_id).getQuanlity();
            book.setQuanlity_Minus_One(_book_id, quanlity - 1);

            //reset field
            jSpinner_IDBook.setValue(0);
            jSpinner_MemberID.setValue(0);
            jLabel_Bookname.setText("Book Name");
            jLabel_MemberName.setText("Member Full Name");
            jTextArea_Note.setText("");
            jDateChooser_Issue_Date.setDate(new Date());
            jDateChooser_ReturnDate.setDate(new Date());
            jTextArea_Note.setText("");

            populateJtableWithissueBooks("");
        } catch (SQLException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Select An Item From The Table", "Select item", 2);
        }

    }//GEN-LAST:event_jButton_LostActionPerformed

    private void jButton_Select_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_MemberActionPerformed
        //search member by id and display his full name:
        int member_id = (int) jSpinner_MemberID.getValue();

        try {
            //get the book id
            My_Classes.Member selectedMember = member.getMemberById(member_id);

            if (selectedMember != null) {
                //display the book title 
                jLabel_MemberName.setText(String.valueOf(selectedMember.getFirstName()) + " " + selectedMember.getLastName());
                //set the member exist to true
                mem_Exist = true;
            } else {
                JOptionPane.showMessageDialog(null, "THIS MEMBER ID DOESN'T EXIST", "Member not found", 2);
                jLabel_MemberName.setText("Member Full Name");
                mem_Exist = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Select_MemberActionPerformed

    private void jButton_Select_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_BookActionPerformed
        //search for the book by ID
        //display the book title
        //check if this book is avalble or not
        int book_id = (int) jSpinner_IDBook.getValue();

        try {
            //get the book id
            My_Classes.Book selectedBook = book.getBookById(book_id);

            if (selectedBook != null) {
                //display the book title 
                jLabel_Bookname.setText(String.valueOf(selectedBook.getName()));
                //set the book exist to true
                book_Exist = true;

            } else {
                jLabel_Bookname.setText("Book Name");
                JOptionPane.showMessageDialog(null, "THIS ID BOOK DOESN'T EXIST", "Book not found", 2);
                book_Exist = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(IssueBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Select_BookActionPerformed

    private void jLabel_BooknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BooknameMouseClicked
        int book_id = (int) jSpinner_IDBook.getValue();
        BookInforCardForm bookInforCardForm = new BookInforCardForm(book_id);
        bookInforCardForm.setVisible(true);
    }//GEN-LAST:event_jLabel_BooknameMouseClicked

    private void jLabel_MemberNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberNameMouseClicked
        int mem_id = (int) jSpinner_MemberID.getValue();
        MemberInforCardForm memberInforCardForm = new MemberInforCardForm(mem_id);
        memberInforCardForm.setVisible(true);
    }//GEN-LAST:event_jLabel_MemberNameMouseClicked

    private void jLabel_BooknameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BooknameMouseEntered
        //add aborder in the bottom of the book name jlable
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(139, 192, 100));
        jLabel_Bookname.setBorder(border);
    }//GEN-LAST:event_jLabel_BooknameMouseEntered

    private void jLabel_BooknameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BooknameMouseExited
        //add aborder in the bottom of the book name jlable
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255, 255, 255));
        jLabel_Bookname.setBorder(border);
    }//GEN-LAST:event_jLabel_BooknameMouseExited

    private void jLabel_MemberNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberNameMouseEntered
        //add aborder in the bottom of the book name jlable
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(139, 192, 100));
        jLabel_MemberName.setBorder(border);
    }//GEN-LAST:event_jLabel_MemberNameMouseEntered

    private void jLabel_MemberNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberNameMouseExited
        //add aborder in the bottom of the book name jlable
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255, 255, 255));
        jLabel_MemberName.setBorder(border);
    }//GEN-LAST:event_jLabel_MemberNameMouseExited

    private void jComboBox_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_StatusActionPerformed
        //display the data on the table depending to the status
        String status = (String) jComboBox_Status.getSelectedItem();
        if (status.equals("All")) {
            status = "";
        }
        populateJtableWithissueBooks(status);
    }//GEN-LAST:event_jComboBox_StatusActionPerformed

    private void jTable_IssueBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_IssueBookMouseClicked
        //display the selected book row data
        //get the selected row index 
        int index = jTable_IssueBook.getSelectedRow();

        //get value
        int book_Id = Integer.parseInt(jTable_IssueBook.getValueAt(index, 0).toString());
        int member_Id = Integer.parseInt(jTable_IssueBook.getValueAt(index, 1).toString());

        My_Classes.Book selectedBook;
        My_Classes.Member selectedMember;

        try {
            selectedBook = book.getBookById(book_Id);

            jSpinner_IDBook.setValue(selectedBook.getBook_id());
            jLabel_Bookname.setText(selectedBook.getName());

            selectedMember = member.getMemberById(member_Id);
            jSpinner_MemberID.setValue(selectedMember.getId());
            jLabel_MemberName.setText(selectedMember.getFirstName() + " " + selectedMember.getLastName());

            //String status = (String) jTable_IssueBook.getValueAt(index, 2);
            String issue_date = (String) jTable_IssueBook.getValueAt(index, 3);
            String return_date = (String) jTable_IssueBook.getValueAt(index, 4);
            String note = (String) jTable_IssueBook.getValueAt(index, 5);

            //display the date
            Date issDate = new SimpleDateFormat("yyyy-MM-dd").parse(issue_date);
            jDateChooser_Issue_Date.setDate(issDate);
            Date reDate = new SimpleDateFormat("yyyy-MM-dd").parse(return_date);
            jDateChooser_ReturnDate.setDate(reDate);

            jTextArea_Note.setText(note);

        } catch (SQLException | ParseException e) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_jTable_IssueBookMouseClicked

    private void jButton_Delete_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_BookActionPerformed
        //delete the selected issue book from the database
        // get the seleted row colum
        int index = jTable_IssueBook.getSelectedRow();

        try {

            int _book_id = Integer.parseInt(jTable_IssueBook.getValueAt(index, 0).toString());
            int _member_id = Integer.parseInt(jTable_IssueBook.getValueAt(index, 1).toString());
            String _Issue_Date = jTable_IssueBook.getValueAt(index, 3).toString();

            issueBook.deleteBookFromIssueTable(_book_id, _member_id, _Issue_Date);
            populateJtableWithissueBooks("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Select Element From The Table ", "Delete Error", 2);
        }


    }//GEN-LAST:event_jButton_Delete_BookActionPerformed

    //creat a function to verify the required fields
    public boolean verif() {
        return true;
    }

    public void populateJtableWithissueBooks(String _status) {
        ArrayList<My_Classes.Issue_Book> issue_BooksList = issueBook.issuedBooksList(_status);

        //jtable collums
        String[] colNames = {"BOOK ID", "MEMBER ID", "STATUS", "ISSUE DATE", "RETURN DATE", "NOTE"};
        //jtable row
        Object[][] rows = new Object[issue_BooksList.size()][colNames.length];

        for (int i = 0; i < issue_BooksList.size(); i++) {
            rows[i][0] = issue_BooksList.get(i).getBook_id();
            rows[i][1] = issue_BooksList.get(i).getMember_id();
            rows[i][2] = issue_BooksList.get(i).getStatus();
            rows[i][3] = issue_BooksList.get(i).getIssue_date();
            rows[i][4] = issue_BooksList.get(i).getReturn_date();
            rows[i][5] = issue_BooksList.get(i).getNote();

        }

        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_IssueBook.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete_Book;
    private javax.swing.JButton jButton_Lost;
    private javax.swing.JButton jButton_Return_Book;
    private javax.swing.JButton jButton_Select_Book;
    private javax.swing.JButton jButton_Select_Member;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private com.toedter.calendar.JDateChooser jDateChooser_Issue_Date;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate;
    private javax.swing.JLabel jLabel_Bookname;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_FirstName1;
    private javax.swing.JLabel jLabel_FirstName2;
    private javax.swing.JLabel jLabel_FirstName7;
    private javax.swing.JLabel jLabel_FirstName8;
    private javax.swing.JLabel jLabel_FirstName9;
    private javax.swing.JLabel jLabel_Form_Title;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_MemberName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_IDBook;
    private javax.swing.JSpinner jSpinner_MemberID;
    private javax.swing.JTable jTable_IssueBook;
    private javax.swing.JTextArea jTextArea_Note;
    // End of variables declaration//GEN-END:variables
}
